version: '3.8'

services:

  php:
    build:
      context: docker
      dockerfile: Dockerfile.dev
    volumes:
      - 'config:/config'
      - '.:/app'
      - '/home/tomas/videos/:/data/'
    ports:
      - '8080:80'
    restart: unless-stopped

volumes:
  config: {}
