version: '3.8'

services:

  php:
    build:
      context: docker
      dockerfile: Dockerfile.dev
    volumes:
      - 'config:/config'
      - '.:/app'
    ports:
      - '8080:80'

volumes:
  config: {}
