FROM php:8.2-cli-alpine

RUN set -xe \
  && apk add --no-cache icu-libs libpng \
  && apk add --no-cache --virtual .build-deps icu-dev libpng-dev \
  && docker-php-ext-install intl gd \
  && apk del --no-network .build-deps

RUN apk add --no-cache beanstalkd ffmpeg supervisor poppler-utils

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

VOLUME ["/config"]

EXPOSE 80

WORKDIR /app
CMD supervisord -c /etc/supervisor/conf.d/supervisord.conf

RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS linux-headers \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del --no-network .build-deps

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --quiet --install-dir=/usr/local/bin/ --filename=composer \
    && rm composer-setup.php
